/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "inverse-surface": "#f8f9ff",
        "tertiary-fixed-dim": "#ab93ff",
        "surface": "#0a0e14",
        "surface-container-lowest": "#000000",
        "surface-bright": "#262c36",
        "on-error": "#490006",
        "outline-variant": "#44484f",
        "on-tertiary-container": "#ffffff",
        "on-error-container": "#ffa8a3",
        "primary-fixed-dim": "#24f07e",
        "primary-dim": "#24f07e",
        "on-tertiary-fixed": "#1c0055",
        "on-secondary-fixed-variant": "#005964",
        "on-primary": "#005d2c",
        "primary-container": "#13ea79",
        "surface-container": "#151a21",
        "on-tertiary": "#25006b",
        "on-background": "#f1f3fc",
        "on-tertiary-fixed-variant": "#4000ad",
        "on-secondary-fixed": "#003a42",
        "on-surface-variant": "#a8abb3",
        "primary": "#3fff8b",
        "secondary": "#00e3fd",
        "inverse-primary": "#006e35",
        "secondary-container": "#006875",
        "secondary-fixed": "#26e6ff",
        "on-surface": "#f1f3fc",
        "tertiary-fixed": "#b8a3ff",
        "error-container": "#9f0519",
        "surface-dim": "#0a0e14",
        "on-primary-fixed-variant": "#006832",
        "on-secondary": "#004d57",
        "tertiary": "#a68cff",
        "tertiary-container": "#7c4dff",
        "secondary-dim": "#00d4ec",
        "error-dim": "#d7383b",
        "on-primary-container": "#004f24",
        "surface-tint": "#3fff8b",
        "surface-container-low": "#0f141a",
        "surface-variant": "#20262f",
        "primary-fixed": "#3fff8b",
        "on-primary-fixed": "#004820",
        "on-secondary-container": "#e8fbff",
        "background": "#0a0e14",
        "error": "#ff716c",
        "surface-container-high": "#1b2028",
        "surface-container-highest": "#20262f",
        "secondary-fixed-dim": "#00d7f0",
        "tertiary-dim": "#7e51ff",
        "inverse-on-surface": "#51555d",
        "outline": "#72757d"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "1.5rem",
        "2xl": "2rem",
        "full": "9999px"
      },
      "fontFamily": {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Space Grotesk", "sans-serif"]
      }
    },
  },
  plugins: [],
}
